/** Canonical lab parameters from body parameters.md — units and bounds are the single source of truth for charts and range checks. */

export type BoundsMode = "between" | "lte" | "gte";

export type ParameterCatalogEntry = {
  key: string;
  section: string;
  label: string;
  unit: string;
  lower: number | null;
  upper: number | null;
  bounds: BoundsMode;
  /** Extra names / abbreviations appearing on lab PDFs — matching is case-insensitive, longest alias wins. */
  aliases: string[];
  /** Reject parsed values outside this window (guards OCR garbage). */
  sanityMin?: number;
  sanityMax?: number;
};

function lipids(): ParameterCatalogEntry[] {
  const s = "Lipid Profile";
  return [
    {
      key: "chol_total",
      section: s,
      label: "Cholesterol, Total",
      unit: "mg/dL",
      lower: 0,
      upper: 200,
      bounds: "lte",
      aliases: ["cholesterol, total", "total cholesterol", "serum cholesterol", "chol total"],
      sanityMin: 50,
      sanityMax: 500,
    },
    {
      key: "triglycerides",
      section: s,
      label: "Triglycerides",
      unit: "mg/dL",
      lower: 0,
      upper: 150,
      bounds: "lte",
      aliases: ["triglycerides", "triglyceride", "tg", "serum tg"],
      sanityMin: 20,
      sanityMax: 2000,
    },
    {
      key: "hdl",
      section: s,
      label: "High-Density Lipoprotein (HDL)",
      unit: "mg/dL",
      lower: 50,
      upper: 300,
      bounds: "gte",
      aliases: ["hdl", "hdl cholesterol", "high-density lipoprotein", "hdl-c", "hdlc"],
      sanityMin: 10,
      sanityMax: 150,
    },
    {
      key: "ldl",
      section: s,
      label: "Low-Density Lipoprotein (LDL)",
      unit: "mg/dL",
      lower: 0,
      upper: 100,
      bounds: "lte",
      aliases: ["ldl", "ldl cholesterol", "low-density lipoprotein", "ldl-c", "ldlc", "calculated ldl"],
      sanityMin: 20,
      sanityMax: 400,
    },
    {
      key: "vldl",
      section: s,
      label: "Very Low-Density Lipoprotein (VLDL)",
      unit: "mg/dL",
      lower: 0,
      upper: 30,
      bounds: "lte",
      aliases: ["vldl", "very low-density lipoprotein", "vldl cholesterol"],
      sanityMin: 2,
      sanityMax: 120,
    },
    {
      key: "chol_hdl_ratio",
      section: s,
      label: "Cholesterol/HDL Ratio",
      unit: "Ratio",
      lower: 3.3,
      upper: 4.4,
      bounds: "between",
      aliases: ["cholesterol/hdl", "chol/hdl", "tc/hdl"],
      sanityMin: 1,
      sanityMax: 15,
    },
    {
      key: "ldl_hdl_ratio",
      section: s,
      label: "LDL/HDL Ratio",
      unit: "Ratio",
      lower: 1.5,
      upper: 3.5,
      bounds: "between",
      aliases: ["ldl/hdl"],
      sanityMin: 0.2,
      sanityMax: 10,
    },
    {
      key: "apo_a1",
      section: s,
      label: "Apolipoprotein - A1 (APO-A1)",
      unit: "mg/dL",
      lower: 86,
      upper: 152,
      bounds: "between",
      aliases: ["apo-a1", "apoa1", "apolipoprotein a1"],
      sanityMin: 40,
      sanityMax: 250,
    },
    {
      key: "apo_b",
      section: s,
      label: "Apolipoprotein - B (APO-B)",
      unit: "mg/dL",
      lower: 56,
      upper: 145,
      bounds: "between",
      aliases: ["apo-b", "apob", "apolipoprotein b"],
      sanityMin: 30,
      sanityMax: 250,
    },
    {
      key: "apo_b_a1",
      section: s,
      label: "APO B / APO A1 Ratio (APO B/A1)",
      unit: "Ratio",
      lower: 0.4,
      upper: 1.26,
      bounds: "between",
      aliases: ["apo b/a1", "apob/apoa1"],
      sanityMin: 0.1,
      sanityMax: 3,
    },
    {
      key: "lp_a",
      section: s,
      label: "Lipoprotein - A (Lp(a))",
      unit: "mg/dL",
      lower: 0,
      upper: 30,
      bounds: "lte",
      aliases: ["lp(a)", "lpa", "lipoprotein a"],
      sanityMin: 1,
      sanityMax: 200,
    },
    {
      key: "hscrp",
      section: s,
      label: "High Sensitivity C-Reactive Protein (hsCRP)",
      unit: "mg/L",
      lower: 0,
      upper: 3,
      bounds: "lte",
      aliases: ["hscrp", "hs-crp", "high sensitivity c-reactive protein"],
      sanityMin: 0,
      sanityMax: 50,
    },
    {
      key: "crp",
      section: s,
      label: "C-Reactive Protein (CRP)",
      unit: "mg/L",
      lower: 0,
      upper: 5,
      bounds: "lte",
      aliases: ["c-reactive protein", "crp"],
      sanityMin: 0,
      sanityMax: 100,
    },
  ];
}

function hematology(): ParameterCatalogEntry[] {
  const s = "Hematology";
  return [
    {
      key: "hemoglobin",
      section: s,
      label: "Hemoglobin (Hb)",
      unit: "g/dL",
      lower: 13,
      upper: 17,
      bounds: "between",
      aliases: ["hemoglobin", "hb", "hgb", "haemoglobin"],
      sanityMin: 5,
      sanityMax: 22,
    },
    {
      key: "rbc",
      section: s,
      label: "Red Blood Cells (RBC) Count",
      unit: "mill/mm³",
      lower: 4.5,
      upper: 5.5,
      bounds: "between",
      aliases: ["rbc count", "red blood cell", "rbc", "erythrocyte count"],
      sanityMin: 3,
      sanityMax: 7,
    },
    {
      key: "hct",
      section: s,
      label: "Hematocrit (HCT) | Packed Cell Volume (PCV)",
      unit: "%",
      lower: 40,
      upper: 50,
      bounds: "between",
      aliases: ["hematocrit", "hct", "packed cell volume", "pcv"],
      sanityMin: 25,
      sanityMax: 65,
    },
    {
      key: "mcv",
      section: s,
      label: "Mean Corpuscular Volume (MCV)",
      unit: "fL",
      lower: 83,
      upper: 101,
      bounds: "between",
      aliases: ["mcv", "mean corpuscular volume"],
      sanityMin: 60,
      sanityMax: 120,
    },
    {
      key: "mch",
      section: s,
      label: "Mean Corpuscular Hemoglobin (MCH)",
      unit: "pg",
      lower: 27,
      upper: 32,
      bounds: "between",
      aliases: ["mch", "mean corpuscular hemoglobin"],
      sanityMin: 20,
      sanityMax: 40,
    },
    {
      key: "mchc",
      section: s,
      label: "Mean Corpuscular Hemoglobin Concentration (MCHC)",
      unit: "g/dL",
      lower: 31.5,
      upper: 34.5,
      bounds: "between",
      aliases: ["mchc"],
      sanityMin: 28,
      sanityMax: 38,
    },
    {
      key: "rdw",
      section: s,
      label: "Red Cell Distribution Width (RDW) CV",
      unit: "%",
      lower: 11.6,
      upper: 14,
      bounds: "between",
      aliases: ["rdw", "rdw-cv", "red cell distribution width"],
      sanityMin: 10,
      sanityMax: 25,
    },
    {
      key: "wbc",
      section: s,
      label: "Total White Blood Cell Count (TC)",
      unit: "cells/mm³",
      lower: 4000,
      upper: 10000,
      bounds: "between",
      aliases: ["total wbc", "wbc count", "white blood cell", "tc", "leukocyte count"],
      sanityMin: 2000,
      sanityMax: 50000,
    },
    {
      key: "neutrophils",
      section: s,
      label: "Neutrophils",
      unit: "%",
      lower: 40,
      upper: 80,
      bounds: "between",
      aliases: ["neutrophils", "neutrophil"],
      sanityMin: 0,
      sanityMax: 100,
    },
    {
      key: "lymphocytes",
      section: s,
      label: "Lymphocytes",
      unit: "%",
      lower: 20,
      upper: 40,
      bounds: "between",
      aliases: ["lymphocytes", "lymphocyte"],
      sanityMin: 0,
      sanityMax: 100,
    },
    {
      key: "monocytes",
      section: s,
      label: "Monocytes",
      unit: "%",
      lower: 2,
      upper: 10,
      bounds: "between",
      aliases: ["monocytes"],
      sanityMin: 0,
      sanityMax: 30,
    },
    {
      key: "eosinophils",
      section: s,
      label: "Eosinophils",
      unit: "%",
      lower: 1,
      upper: 6,
      bounds: "between",
      aliases: ["eosinophils"],
      sanityMin: 0,
      sanityMax: 20,
    },
    {
      key: "basophils",
      section: s,
      label: "Basophils",
      unit: "%",
      lower: 0,
      upper: 2,
      bounds: "between",
      aliases: ["basophils"],
      sanityMin: 0,
      sanityMax: 5,
    },
    {
      key: "platelets",
      section: s,
      label: "Platelet Count",
      unit: "10^3 /µL",
      lower: 150,
      upper: 450,
      bounds: "between",
      aliases: ["platelet count", "platelets", "plt"],
      sanityMin: 20,
      sanityMax: 800,
    },
    {
      key: "ana",
      section: s,
      label: "Anti Nuclear Antibodies (ANA)",
      unit: "AU/mL",
      lower: 0,
      upper: 25,
      bounds: "lte",
      aliases: ["ana", "anti nuclear antibodies"],
      sanityMin: 0,
      sanityMax: 500,
    },
    {
      key: "acca",
      section: s,
      label: "Anti CCP (ACCP)",
      unit: "AU/mL",
      lower: 0,
      upper: 10,
      bounds: "lte",
      aliases: ["anti-ccp", "acca", "anti ccp"],
      sanityMin: 0,
      sanityMax: 200,
    },
    {
      key: "ferritin",
      section: s,
      label: "Ferritin",
      unit: "ng/mL",
      lower: 21.81,
      upper: 274.66,
      bounds: "between",
      aliases: ["ferritin"],
      sanityMin: 5,
      sanityMax: 2000,
    },
    {
      key: "esr",
      section: s,
      label: "Erythrocyte Sedimentation Rate (ESR)",
      unit: "mm/hr",
      lower: 0,
      upper: 10,
      bounds: "lte",
      aliases: ["esr", "erythrocyte sedimentation rate"],
      sanityMin: 0,
      sanityMax: 150,
    },
  ];
}

function lft(): ParameterCatalogEntry[] {
  const s = "Liver Function Test (LFT)";
  return [
    {
      key: "bilirubin_total",
      section: s,
      label: "Bilirubin, Total",
      unit: "mg/dL",
      lower: 0.2,
      upper: 1.3,
      bounds: "between",
      aliases: ["bilirubin total", "total bilirubin", "tbil"],
      sanityMin: 0,
      sanityMax: 30,
    },
    {
      key: "bilirubin_direct",
      section: s,
      label: "Bilirubin, Direct",
      unit: "mg/dL",
      lower: 0,
      upper: 0.3,
      bounds: "lte",
      aliases: ["direct bilirubin", "bilirubin direct", "dbil"],
      sanityMin: 0,
      sanityMax: 15,
    },
    {
      key: "bilirubin_indirect",
      section: s,
      label: "Bilirubin, Indirect",
      unit: "mg/dL",
      lower: 0.1,
      upper: 1.1,
      bounds: "between",
      aliases: ["indirect bilirubin", "bilirubin indirect"],
      sanityMin: 0,
      sanityMax: 15,
    },
    {
      key: "ast",
      section: s,
      label: "Aspartate Aminotransferase (AST)",
      unit: "U/L",
      lower: 17,
      upper: 49,
      bounds: "between",
      aliases: ["ast", "sgot", "aspartate aminotransferase"],
      sanityMin: 5,
      sanityMax: 2000,
    },
    {
      key: "alt",
      section: s,
      label: "Alanine Transaminase (ALT)",
      unit: "U/L",
      lower: 0,
      upper: 50,
      bounds: "lte",
      aliases: ["alt", "sgpt", "alanine transaminase"],
      sanityMin: 5,
      sanityMax: 2000,
    },
    {
      key: "alp",
      section: s,
      label: "Alkaline Phosphatase (ALP)",
      unit: "U/L",
      lower: 38,
      upper: 126,
      bounds: "between",
      aliases: ["alp", "alkaline phosphatase"],
      sanityMin: 20,
      sanityMax: 500,
    },
    {
      key: "ggt",
      section: s,
      label: "Gamma-Glutamyl Transpeptidase (GGT)",
      unit: "U/L",
      lower: 15,
      upper: 73,
      bounds: "between",
      aliases: ["ggt", "gamma gt", "gamma-glutamyl transpeptidase"],
      sanityMin: 5,
      sanityMax: 500,
    },
    {
      key: "protein_total",
      section: s,
      label: "Protein",
      unit: "g/dL",
      lower: 6,
      upper: 8.3,
      bounds: "between",
      aliases: ["serum protein", "total protein", "protein"],
      sanityMin: 4,
      sanityMax: 12,
    },
    {
      key: "albumin",
      section: s,
      label: "Albumin",
      unit: "g/dL",
      lower: 3.5,
      upper: 5,
      bounds: "between",
      aliases: ["albumin", "serum albumin"],
      sanityMin: 2,
      sanityMax: 6,
    },
    {
      key: "globulin",
      section: s,
      label: "Globulin",
      unit: "g/dL",
      lower: 2.3,
      upper: 3.5,
      bounds: "between",
      aliases: ["globulin", "serum globulin"],
      sanityMin: 1,
      sanityMax: 6,
    },
    {
      key: "ag_ratio",
      section: s,
      label: "Albumin/Globulin (A/G) Ratio",
      unit: "Ratio",
      lower: 0.8,
      upper: 2,
      bounds: "between",
      aliases: ["a/g ratio", "albumin/globulin", "ag ratio", "a:g ratio"],
      sanityMin: 0.3,
      sanityMax: 4,
    },
    {
      key: "aat",
      section: s,
      label: "Alpha-1-Antitrypsin (AAT)",
      unit: "mg/dL",
      lower: 90,
      upper: 200,
      bounds: "between",
      aliases: ["alpha-1-antitrypsin", "aat"],
      sanityMin: 30,
      sanityMax: 350,
    },
  ];
}

function kft(): ParameterCatalogEntry[] {
  const s = "Kidney Function Test (KFT)";
  return [
    {
      key: "urea",
      section: s,
      label: "Urea",
      unit: "mg/dL",
      lower: 19,
      upper: 43,
      bounds: "between",
      aliases: ["urea", "blood urea"],
      sanityMin: 5,
      sanityMax: 200,
    },
    {
      key: "creatinine",
      section: s,
      label: "Creatinine",
      unit: "mg/dL",
      lower: 0.66,
      upper: 1.25,
      bounds: "between",
      aliases: ["creatinine", "serum creatinine", "s creatinine"],
      sanityMin: 0.3,
      sanityMax: 15,
    },
    {
      key: "bun",
      section: s,
      label: "Blood Urea Nitrogen (BUN)",
      unit: "mg/dL",
      lower: 6,
      upper: 20,
      bounds: "between",
      aliases: ["bun", "blood urea nitrogen"],
      sanityMin: 2,
      sanityMax: 120,
    },
    {
      key: "bun_creatinine_ratio",
      section: s,
      label: "Blood Urea Nitrogen (BUN)/Creatinine Ratio",
      unit: "Ratio",
      lower: 10,
      upper: 20,
      bounds: "between",
      aliases: ["bun/creatinine", "bun creatinine ratio"],
      sanityMin: 5,
      sanityMax: 50,
    },
    {
      key: "uric_acid",
      section: s,
      label: "Uric Acid",
      unit: "mg/dL",
      lower: 3.5,
      upper: 8.5,
      bounds: "between",
      aliases: ["uric acid", "serum uric acid"],
      sanityMin: 1,
      sanityMax: 15,
    },
    {
      key: "calcium",
      section: s,
      label: "Calcium",
      unit: "mg/dL",
      lower: 8.4,
      upper: 10.2,
      bounds: "between",
      aliases: ["calcium", "serum calcium", "total calcium"],
      sanityMin: 6,
      sanityMax: 14,
    },
    {
      key: "phosphorus",
      section: s,
      label: "Phosphorus",
      unit: "mg/dL",
      lower: 2.5,
      upper: 4.5,
      bounds: "between",
      aliases: ["phosphorus", "phosphate", "serum phosphorus"],
      sanityMin: 1,
      sanityMax: 8,
    },
    {
      key: "cystatin_c",
      section: s,
      label: "Cystatin C",
      unit: "mg/L",
      lower: 0,
      upper: 1.03,
      bounds: "lte",
      aliases: ["cystatin c"],
      sanityMin: 0.3,
      sanityMax: 5,
    },
    {
      key: "egfr",
      section: s,
      label: "Estimated Glomerular Filtration Rate (eGFR)",
      unit: "mL/min/1.73m²",
      lower: 90,
      upper: 200,
      bounds: "gte",
      aliases: ["egfr", "gfr", "estimated gfr", "glomerular filtration rate"],
      sanityMin: 5,
      sanityMax: 180,
    },
  ];
}

function diabetes(): ParameterCatalogEntry[] {
  const s = "Diabetes";
  return [
    {
      key: "hba1c",
      section: s,
      label: "Glycated Hemoglobin (HbA1C)",
      unit: "%",
      lower: 0,
      upper: 5.7,
      bounds: "lte",
      aliases: ["hba1c", "hb a1c", "glycated hemoglobin", "a1c", "glycosylated hemoglobin"],
      sanityMin: 3,
      sanityMax: 18,
    },
    {
      key: "mean_blood_glucose",
      section: s,
      label: "Mean Blood Glucose",
      unit: "mg/dL",
      lower: 0,
      upper: 117,
      bounds: "lte",
      aliases: ["mean blood glucose", "estimated average glucose", "eag"],
      sanityMin: 50,
      sanityMax: 400,
    },
    {
      key: "glucose_fasting",
      section: s,
      label: "Glocose, Fasting",
      unit: "mg/dL",
      lower: 70,
      upper: 100,
      bounds: "between",
      aliases: ["fasting glucose", "fasting blood sugar", "fbs", "glucose fasting", "glucose (f)"],
      sanityMin: 40,
      sanityMax: 500,
    },
    {
      key: "glucose_random",
      section: s,
      label: "Glucose, Random",
      unit: "mg/dL",
      lower: 70,
      upper: 140,
      bounds: "between",
      aliases: ["random glucose", "glucose random", "rbs"],
      sanityMin: 40,
      sanityMax: 600,
    },
    {
      key: "insulin_fasting",
      section: s,
      label: "Insulin - Fasting",
      unit: "µU/mL",
      lower: 2.6,
      upper: 24.9,
      bounds: "between",
      aliases: ["fasting insulin", "insulin fasting", "serum insulin"],
      sanityMin: 0.5,
      sanityMax: 100,
    },
    {
      key: "blood_ketone",
      section: s,
      label: "Blood Ketone (D3HB)",
      unit: "mg/dL",
      lower: 0.21,
      upper: 2.81,
      bounds: "between",
      aliases: ["blood ketone", "d3hb", "beta-hydroxybutyrate"],
      sanityMin: 0,
      sanityMax: 10,
    },
    {
      key: "fructosamine",
      section: s,
      label: "Fructosamine",
      unit: "µmol/L",
      lower: 0,
      upper: 286,
      bounds: "lte",
      aliases: ["fructosamine"],
      sanityMin: 100,
      sanityMax: 500,
    },
  ];
}

function tft(): ParameterCatalogEntry[] {
  const s = "Thyroid Function Test (TFT)";
  return [
    {
      key: "t3_total",
      section: s,
      label: "Triiodothyronine (T3), Total",
      unit: "ng/mL",
      lower: 0.97,
      upper: 1.69,
      bounds: "between",
      aliases: ["t3, total", "t3 total", "total t3", "triiodothyronine", "serum t3"],
      sanityMin: 0.1,
      sanityMax: 8,
    },
    {
      key: "t4_total",
      section: s,
      label: "Thyroxine (T4), Total",
      unit: "µg/dL",
      lower: 5.53,
      upper: 11,
      bounds: "between",
      aliases: ["t4, total", "t4 total", "total t4", "thyroxine", "serum t4"],
      sanityMin: 2,
      sanityMax: 25,
    },
    {
      key: "tsh",
      section: s,
      label: "Thyroid Stimulating Hormone (TSH)",
      unit: "µIU/mL",
      lower: 0.4,
      upper: 4.049,
      bounds: "between",
      aliases: ["tsh", "thyroid stimulating hormone"],
      sanityMin: 0.01,
      sanityMax: 50,
    },
    {
      key: "iodine",
      section: s,
      label: "Iodine",
      unit: "mcg/L",
      lower: 31.1,
      upper: 64.6,
      bounds: "between",
      aliases: ["iodine"],
      sanityMin: 10,
      sanityMax: 200,
    },
  ];
}

function vitaminsHormones(): ParameterCatalogEntry[] {
  const s = "Vitamins & Hormones";
  return [
    { key: "vitamin_a", section: s, label: "Vitamin A", unit: "ng/mL", lower: 300, upper: 800, bounds: "between", aliases: ["vitamin a", "retinol"], sanityMin: 50, sanityMax: 5000 },
    { key: "vitamin_b1", section: s, label: "Vitamin B1 (Thiamin)", unit: "ng/mL", lower: 0.5, upper: 4, bounds: "between", aliases: ["vitamin b1", "thiamin", "thiamine"], sanityMin: 0.1, sanityMax: 20 },
    { key: "vitamin_b2", section: s, label: "Vitamin B2 (Riboflavin)", unit: "ng/mL", lower: 1.6, upper: 68.2, bounds: "between", aliases: ["vitamin b2", "riboflavin"], sanityMin: 0.5, sanityMax: 200 },
    { key: "vitamin_b3", section: s, label: "Vitamin B3 (Nicotinic Acid)", unit: "ng/mL", lower: 0.3, upper: 9.8, bounds: "between", aliases: ["vitamin b3", "nicotinic acid", "niacin"], sanityMin: 0.1, sanityMax: 50 },
    { key: "vitamin_b5", section: s, label: "Vitamin B5 (Pantothenic)", unit: "ng/mL", lower: 11, upper: 150, bounds: "between", aliases: ["vitamin b5", "pantothenic"], sanityMin: 1, sanityMax: 300 },
    { key: "vitamin_b6", section: s, label: "Vitamin B6 (P5P)", unit: "ng/mL", lower: 5, upper: 50, bounds: "between", aliases: ["vitamin b6", "p5p"], sanityMin: 1, sanityMax: 200 },
    { key: "vitamin_b7", section: s, label: "Vitamin B7 (Biotin)", unit: "ng/mL", lower: 0.2, upper: 3, bounds: "between", aliases: ["vitamin b7", "biotin"], sanityMin: 0.05, sanityMax: 20 },
    { key: "vitamin_b9", section: s, label: "Vitamin B9 (Folic Acid)", unit: "ng/mL", lower: 0.2, upper: 20, bounds: "between", aliases: ["vitamin b9", "folic acid", "folate"], sanityMin: 0.1, sanityMax: 50 },
    { key: "vitamin_b12", section: s, label: "Vitamin B12", unit: "ng/mL", lower: 239, upper: 931, bounds: "between", aliases: ["vitamin b12", "b12", "cobalamin"], sanityMin: 50, sanityMax: 2000 },
    { key: "vitamin_c", section: s, label: "Vitamin C (Ascorbic Acid)", unit: "ng/mL", lower: 200, upper: 2000, bounds: "between", aliases: ["vitamin c", "ascorbic acid"], sanityMin: 50, sanityMax: 10000 },
    {
      key: "vitamin_d",
      section: s,
      label: "Vitamin D, 25-Hydroxy",
      unit: "ng/mL",
      lower: 30,
      upper: 100,
      bounds: "between",
      aliases: ["vitamin d", "25-hydroxy vitamin d", "25-oh vitamin d", "vit d", "25(oh)d", "25 oh vitamin d"],
      sanityMin: 3,
      sanityMax: 200,
    },
    { key: "vitamin_e", section: s, label: "Vitamin E", unit: "ng/mL", lower: 5500, upper: 18000, bounds: "between", aliases: ["vitamin e", "tocopherol"], sanityMin: 1000, sanityMax: 50000 },
    { key: "vitamin_k", section: s, label: "Vitamin K", unit: "ng/mL", lower: 0.13, upper: 1.19, bounds: "between", aliases: ["vitamin k"], sanityMin: 0.01, sanityMax: 10 },
    { key: "testosterone", section: s, label: "Testosterone", unit: "ng/mL", lower: 132, upper: 813, bounds: "between", aliases: ["testosterone", "serum testosterone"], sanityMin: 10, sanityMax: 2000 },
    { key: "prolactin", section: s, label: "Prolactin", unit: "ng/mL", lower: 2.64, upper: 13.13, bounds: "between", aliases: ["prolactin"], sanityMin: 0.5, sanityMax: 100 },
    { key: "zinc", section: s, label: "Zinc", unit: "mcg/dL", lower: 74, upper: 120, bounds: "between", aliases: ["zinc", "serum zinc"], sanityMin: 30, sanityMax: 250 },
    { key: "copper", section: s, label: "Copper", unit: "µg/dL", lower: 70, upper: 140, bounds: "between", aliases: ["copper", "serum copper"], sanityMin: 30, sanityMax: 300 },
    { key: "manganese", section: s, label: "Manganese", unit: "µg/L", lower: 4, upper: 15, bounds: "between", aliases: ["manganese"], sanityMin: 1, sanityMax: 50 },
    { key: "selenium", section: s, label: "Selenium", unit: "mcg/L", lower: 110, upper: 165, bounds: "between", aliases: ["selenium"], sanityMin: 20, sanityMax: 500 },
    { key: "chromium", section: s, label: "Chromium", unit: "µg/L", lower: 0, upper: 1.4, bounds: "lte", aliases: ["chromium"], sanityMin: 0, sanityMax: 10 },
    { key: "molybdenum", section: s, label: "Molybdenum", unit: "ng/mL", lower: 0, upper: 3.3, bounds: "lte", aliases: ["molybdenum"], sanityMin: 0, sanityMax: 20 },
    { key: "fluoride", section: s, label: "Fluoride", unit: "µmol/L", lower: 0.21, upper: 2.11, bounds: "between", aliases: ["fluoride"], sanityMin: 0, sanityMax: 10 },
    { key: "boron", section: s, label: "Boron", unit: "µg/L", lower: 31.2, upper: 33.5, bounds: "between", aliases: ["boron"], sanityMin: 5, sanityMax: 100 },
  ];
}

function electrolytes(): ParameterCatalogEntry[] {
  const s = "Electrolytes";
  return [
    { key: "sodium", section: s, label: "Sodium", unit: "mmol/L", lower: 137, upper: 145, bounds: "between", aliases: ["sodium", "na+", "serum sodium"], sanityMin: 110, sanityMax: 180 },
    { key: "potassium", section: s, label: "Potassium", unit: "mmol/L", lower: 3.5, upper: 5.5, bounds: "between", aliases: ["potassium", "k+", "serum potassium"], sanityMin: 2, sanityMax: 8 },
    { key: "chloride", section: s, label: "Chloride", unit: "mmol/L", lower: 98, upper: 107, bounds: "between", aliases: ["chloride", "cl-", "serum chloride"], sanityMin: 70, sanityMax: 130 },
    { key: "magnesium", section: s, label: "Magnesium", unit: "mg/dL", lower: 1.7, upper: 2.2, bounds: "between", aliases: ["magnesium", "serum magnesium"], sanityMin: 0.5, sanityMax: 5 },
  ];
}

function cancer(): ParameterCatalogEntry[] {
  const s = "Cancer Screening";
  return [
    { key: "cea", section: s, label: "Carcinoembryonic Antigen (CEA)", unit: "ng/mL", lower: 0, upper: 3, bounds: "lte", aliases: ["cea", "carcinoembryonic antigen"], sanityMin: 0, sanityMax: 500 },
    { key: "ca199", section: s, label: "CA 19.9 (Pancreatic Cancer Marker)", unit: "U/mL", lower: 0, upper: 37, bounds: "lte", aliases: ["ca 19-9", "ca19-9", "ca 19.9"], sanityMin: 0, sanityMax: 10000 },
    { key: "psa", section: s, label: "Prostate-Specific Antigen (PSA) Total", unit: "ng/mL", lower: 0, upper: 1.4, bounds: "lte", aliases: ["psa", "prostate specific antigen", "psa total"], sanityMin: 0, sanityMax: 100 },
  ];
}

function iron(): ParameterCatalogEntry[] {
  const s = "Iron Profile";
  return [
    { key: "iron", section: s, label: "Iron", unit: "µg/dL", lower: 49, upper: 181, bounds: "between", aliases: ["serum iron", "iron"], sanityMin: 10, sanityMax: 400 },
    { key: "tibc", section: s, label: "Total Iron Binding Capacity (TIBC)", unit: "µg/dL", lower: 261, upper: 462, bounds: "between", aliases: ["tibc", "total iron binding capacity"], sanityMin: 100, sanityMax: 700 },
    { key: "uibc", section: s, label: "Unbound Iron Binding Capacity (UIBC)", unit: "µg/dL", lower: 110, upper: 371, bounds: "between", aliases: ["uibc"], sanityMin: 50, sanityMax: 500 },
    { key: "tsat", section: s, label: "Transferrin Saturation (TSAT)", unit: "%", lower: 16, upper: 55, bounds: "between", aliases: ["transferrin saturation", "tsat", "iron saturation"], sanityMin: 5, sanityMax: 100 },
  ];
}

export const PARAMETER_CATALOG: ParameterCatalogEntry[] = [
  ...lipids(),
  ...hematology(),
  ...lft(),
  ...kft(),
  ...diabetes(),
  ...tft(),
  ...vitaminsHormones(),
  ...electrolytes(),
  ...cancer(),
  ...iron(),
];

/** Section order for dashboard table (matches body parameters.md). */
export const SECTION_ORDER = [
  "Lipid Profile",
  "Hematology",
  "Liver Function Test (LFT)",
  "Kidney Function Test (KFT)",
  "Diabetes",
  "Thyroid Function Test (TFT)",
  "Vitamins & Hormones",
  "Electrolytes",
  "Cancer Screening",
  "Iron Profile",
] as const;

export const PARAMETER_BY_KEY: Map<string, ParameterCatalogEntry> = new Map(
  PARAMETER_CATALOG.map((p) => [p.key, p]),
);

export const DEFAULT_CHART_KEYS = [
  ["ldl", "hdl", "vldl", "triglycerides"],
  ["hemoglobin"],
  ["hba1c"],
  ["vitamin_d"],
  ["ag_ratio"],
  ["t3_total"],
  ["t4_total"],
] as const;

export function isValueOutOfRange(value: number, p: ParameterCatalogEntry): boolean {
  if (p.bounds === "between" && p.lower != null && p.upper != null) {
    return value < p.lower || value > p.upper;
  }
  if (p.bounds === "lte" && p.upper != null) {
    return value > p.upper;
  }
  if (p.bounds === "gte" && p.lower != null) {
    return value < p.lower;
  }
  return false;
}
